"""Markdown + folium reports for baseline vs. scenario comparisons."""

from __future__ import annotations

from pathlib import Path

import branca.colormap as cm
import folium
import numpy as np
import pandas as pd

from leonia_traffic.network.osm_builder import parse_uxsim_link_name


def _link_latlon(W, link_name: str) -> list[tuple[float, float]] | None:
    try:
        link = W.get_link(link_name)
    except Exception:
        return None
    return [
        (link.start_node.y, link.start_node.x),
        (link.end_node.y, link.end_node.x),
    ]


def delta_map(
    W_baseline,
    delta_df: pd.DataFrame,
    *,
    column: str = "delta_vph",
    label: str = "Δ flow (veh/h)",
    center: tuple[float, float] = (40.864, -73.985),
) -> folium.Map:
    """Render a folium map showing the per-link flow delta."""
    fmap = folium.Map(location=center, zoom_start=14, tiles="CartoDB positron")
    vals = delta_df[column].to_numpy()
    finite = vals[np.isfinite(vals)]
    if len(finite) == 0:
        return fmap
    span = max(float(np.quantile(np.abs(finite), 0.95)), 50.0)
    colormap = cm.LinearColormap(
        colors=["#2166ac", "#67a9cf", "#f7f7f7", "#ef8a62", "#b2182b"],
        vmin=-span,
        vmax=span,
        caption=label,
    )
    for link_name, row in delta_df.iterrows():
        coords = _link_latlon(W_baseline, link_name)
        if coords is None:
            continue
        v = float(row[column])
        if not np.isfinite(v) or abs(v) < 5:
            continue
        color = colormap(max(min(v, span), -span))
        road_name, osmid, _ = parse_uxsim_link_name(str(link_name))
        folium.PolyLine(
            locations=coords,
            color=color,
            weight=4 + min(abs(v) / span * 4, 4),
            opacity=0.85,
            tooltip=(
                f"{road_name}<br>"
                f"baseline: {row.get('sim_flow_baseline_vph', 0):.0f} veh/h<br>"
                f"scenario: {row.get('sim_flow_scenario_vph', 0):.0f} veh/h<br>"
                f"delta: {v:+.0f} veh/h"
            ),
        ).add_to(fmap)
    fmap.add_child(colormap)
    return fmap


def _format_score(s) -> dict[str, str]:
    return {
        "geh_mean": f"{s.geh_mean:.2f}",
        "geh_p85": f"{s.geh_p85:.2f}",
        "pct_lt_5": f"{s.pct_lt_5 * 100:.1f}%",
        "pct_lt_10": f"{s.pct_lt_10 * 100:.1f}%",
        "n_links_scored": str(s.n_links_scored),
    }


def write_scenario_report(
    *,
    baseline_result,
    scenario_result,
    delta_df: pd.DataFrame,
    out_md: Path,
    map_html: Path | None,
    n_top: int = 20,
) -> None:
    lines: list[str] = []
    lines.append(f"# Scenario: {scenario_result.name}\n")
    lines.append(
        "_Auto-generated by `leonia_traffic.analysis.reports.write_scenario_report`. "
        "Baseline and scenario simulations use the same demand model and random seed; "
        "the only differences are the network edits enumerated in the scenario._\n"
    )

    lines.append("## Calibration scores\n")
    lines.append("| Metric | Baseline | Scenario |\n| --- | --- | --- |")
    b = _format_score(baseline_result.score)
    s = _format_score(scenario_result.score)
    for k in b:
        lines.append(f"| {k} | {b[k]} | {s[k]} |")
    lines.append("")

    lines.append("## Top impacted links (by |Δ flow|)\n")
    top = delta_df.head(n_top).copy()
    cols = [
        ("osm_way_id", "OSM way"),
        ("sim_flow_baseline_vph", "Baseline veh/h"),
        ("sim_flow_scenario_vph", "Scenario veh/h"),
        ("delta_vph", "Δ veh/h"),
        ("observed_volume_daily", "Observed daily"),
        ("spillover_flag", "Spillover?"),
    ]
    header = "| Road / OSM | " + " | ".join(c[1] for c in cols) + " |"
    sep = "| --- | " + " | ".join(["---"] * len(cols)) + " |"
    lines.append(header)
    lines.append(sep)
    for link_name, row in top.iterrows():
        road, osmid, _ = parse_uxsim_link_name(str(link_name))
        if not road or road.startswith("#"):
            road = "(unnamed road)"
        row_cells = [f"{road}"]
        for k, _ in cols:
            v = row.get(k)
            if v is None or (isinstance(v, float) and not np.isfinite(v)):
                row_cells.append("")
            elif isinstance(v, float):
                row_cells.append(f"{v:+,.0f}" if k == "delta_vph" else f"{v:,.0f}")
            elif isinstance(v, bool):
                row_cells.append("yes" if v else "")
            else:
                row_cells.append(str(v))
        lines.append("| " + " | ".join(row_cells) + " |")
    lines.append("")

    if "spillover_flag" in delta_df.columns:
        spill = delta_df[delta_df["spillover_flag"]].head(20)
        lines.append("## Spillover warnings (residential streets gaining flow)\n")
        if spill.empty:
            lines.append("_None detected by the heuristic._")
        else:
            lines.append("| Road / OSM | Baseline veh/h | Scenario veh/h | Δ veh/h |")
            lines.append("| --- | --- | --- | --- |")
            for link_name, row in spill.iterrows():
                road, _, _ = parse_uxsim_link_name(str(link_name))
                if not road or road.startswith("#"):
                    road = "(unnamed road)"
                lines.append(
                    f"| {road} | {row['sim_flow_baseline_vph']:.0f} | "
                    f"{row['sim_flow_scenario_vph']:.0f} | "
                    f"{row['delta_vph']:+.0f} |"
                )
        lines.append("")

    if map_html is not None:
        rel = Path(map_html).name
        lines.append(f"## Map\n\n- Interactive: `reports/maps/{rel}`")
        lines.append("")

    out_md.write_text("\n".join(lines), encoding="utf-8")


__all__ = ["delta_map", "write_scenario_report"]
