"""Extract a compact flow dataset for the front-end prototypes.

Reads a real Leonia SUMO baseline run (per-edge, per-bin vehicle counts)
plus the network geometry, aggregates to 15-minute frames of vehicles-per-
hour (reusing the exact same logic the production folium animation uses),
and writes a small ``leonia_flow_data.js`` that both prototype HTML files
load with a plain ``<script src>`` (so they open from ``file://`` with no
local server and no CORS headache).

Run from the repo root:

    venv/bin/python prototypes/extract_flow_data.py

Optional flags let you point at a different run or tune the size of the
emitted payload.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

from leonia_traffic.sumo.visualizations import build_flow_payload

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RUN = (
    REPO_ROOT
    / "data/sumo/runs/20260522T041939Z_baseline/edge_history.parquet"
)
DEFAULT_NET = REPO_ROOT / "data/sumo/base/leonia.net.xml"
OUT_JS = Path(__file__).resolve().parent / "leonia_flow_data.js"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--run", type=Path, default=DEFAULT_RUN,
                    help="edge_history.parquet to read")
    ap.add_argument("--net", type=Path, default=DEFAULT_NET,
                    help="leonia.net.xml for edge geometry")
    ap.add_argument("--frame-minutes", type=int, default=15)
    ap.add_argument("--min-vph", type=float, default=20.0,
                    help="an edge needs at least this peak vph across the "
                         "day to be promoted to an animated 'active' edge")
    ap.add_argument("--max-skeleton", type=int, default=4000,
                    help="cap on context (grey) edges to keep the file small")
    args = ap.parse_args()

    print(f"Loading edge history from {args.run} ...")
    hist = pd.read_parquet(args.run)
    print(f"Building flow payload (net: {args.net}) ...")
    payload = build_flow_payload(
        hist,
        args.net,
        frame_minutes=args.frame_minutes,
        min_vph=args.min_vph,
        max_skeleton=args.max_skeleton,
        title="Leonia simulated traffic — baseline",
    )

    OUT_JS.write_text(
        "// Auto-generated by prototypes/extract_flow_data.py — do not edit.\n"
        "window.LEONIA_FLOW = " + json.dumps(payload, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    meta = payload["meta"]
    size_mb = OUT_JS.stat().st_size / 1e6
    print(f"\nWrote {OUT_JS}  ({size_mb:.2f} MB)")
    print(f"  active edges: {meta['n_active_edges']}  "
          f"skeleton: {len(payload['skeleton'])}  "
          f"frames: {meta['n_frames']}  vmax_vph: {meta['vmax_vph']}")


if __name__ == "__main__":
    main()
