"""Phase 2: build the Leonia OSM→UXsim network and write a diagnostic report.

Run from the repo root:

    venv/bin/python scripts/02_build_network.py [--rebuild]

Outputs:

    data/network/leonia_osm_network.pkl
    reports/02_network.md
    reports/figures/network_raw.png
    reports/figures/network_postprocessed.png
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from leonia_traffic.config import (
    DATA_NETWORK_DIR,
    LEONIA_BBOX_WGS84,
    REPORTS_DIR,
    REPORTS_FIG_DIR,
)
from leonia_traffic.data.streetlight_loader import load_cached, restrict_to_study_area
from leonia_traffic.network.calibration_match import match_segments_to_links
from leonia_traffic.network.osm_builder import (
    DEFAULT_HIGHWAY_FILTER,
    OSMBuildConfig,
    build_or_load_network,
    summarize_network,
)


def _plot_links(nodes: list, links: list, title: str, out_path: Path) -> None:
    node_xy = {n[0]: (n[1], n[2]) for n in nodes}
    fig, ax = plt.subplots(figsize=(9, 9))
    for link in links:
        a = node_xy.get(link[1])
        b = node_xy.get(link[2])
        if a is None or b is None:
            continue
        ax.plot([a[0], b[0]], [a[1], b[1]], color="#444", linewidth=0.6, alpha=0.8)
    xs = [xy[0] for xy in node_xy.values()]
    ys = [xy[1] for xy in node_xy.values()]
    ax.scatter(xs, ys, s=3, color="#1f77b4", alpha=0.6)
    ax.set_aspect("equal", adjustable="datalim")
    ax.set_title(title)
    ax.set_xlabel("Longitude")
    ax.set_ylabel("Latitude")
    fig.tight_layout()
    fig.savefig(out_path, dpi=120)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--rebuild", action="store_true", help="Force re-download from OSM")
    args = parser.parse_args()

    cfg = OSMBuildConfig(
        bbox_wgs84=LEONIA_BBOX_WGS84,
        highway_filter=DEFAULT_HIGHWAY_FILTER,
        node_merge_threshold_deg=0.0005,
        node_merge_iteration=5,
        enforce_bidirectional=False,
        overrides_path=DATA_NETWORK_DIR / "overrides.yaml",
    )

    print(f"Building network for bbox={cfg.bbox_wgs84}")
    nodes, links, cfg = build_or_load_network(cfg, rebuild=args.rebuild)

    summary = summarize_network(nodes, links)
    print("Network summary:")
    for k, v in summary.items():
        print(f"  {k}: {v}")

    print("Rendering network figure...")
    _plot_links(
        nodes,
        links,
        f"Leonia study area network (postprocessed)\n"
        f"{summary['n_nodes']} nodes, {summary['n_links']} links, "
        f"{summary['n_unique_osm_ways']} OSM ways",
        REPORTS_FIG_DIR / "network_postprocessed.png",
    )

    print("Loading StreetLight data and matching to UXsim links...")
    gdf = restrict_to_study_area(load_cached())
    matched = match_segments_to_links(gdf, links, source_label="weekdays")

    n_links_total = len(links)
    n_links_matched = len(matched)
    n_links_unmatched = n_links_total - n_links_matched

    write_report(
        cfg=cfg,
        summary=summary,
        matched=matched,
        n_links_total=n_links_total,
        n_links_matched=n_links_matched,
        n_links_unmatched=n_links_unmatched,
    )
    print(f"Done. See {REPORTS_DIR / '02_network.md'}")


def write_report(
    *,
    cfg,
    summary,
    matched,
    n_links_total,
    n_links_matched,
    n_links_unmatched,
) -> None:
    lines: list[str] = []
    lines.append("# Phase 2 — OSM → UXsim network\n")
    lines.append(
        "_Auto-generated by `scripts/02_build_network.py`. The network is "
        "cached at `data/network/leonia_osm_network.pkl`. Pass `--rebuild` "
        "to re-download from OSM._\n"
    )

    lines.append("## Build configuration\n")
    lines.append("| Parameter | Value |\n| --- | --- |")
    for k, v in [
        ("bbox (lon/lat)", cfg.bbox_wgs84),
        ("highway filter", f"`{cfg.highway_filter}`"),
        ("node_merge_threshold_deg", cfg.node_merge_threshold_deg),
        ("node_merge_iteration", cfg.node_merge_iteration),
        ("enforce_bidirectional", cfg.enforce_bidirectional),
        ("overrides_path", cfg.overrides_path),
    ]:
        lines.append(f"| {k} | {v} |")
    lines.append("")

    lines.append("## Network statistics\n")
    lines.append("| Metric | Count |\n| --- | --- |")
    for k, v in summary.items():
        lines.append(f"| {k} | {v:,} |")
    lines.append("")
    lines.append("![Network map](figures/network_postprocessed.png)\n")

    lines.append("## StreetLight ↔ UXsim link coverage\n")
    lines.append(
        f"- Total UXsim links: **{n_links_total:,}**\n"
        f"- Matched to ≥1 StreetLight Weekday zone: **{n_links_matched:,}** "
        f"({n_links_matched / max(n_links_total, 1):.1%})\n"
        f"- Unmatched: **{n_links_unmatched:,}**"
    )
    lines.append("")

    if not matched.empty:
        cov = matched.groupby("n_streetlight_zones").size().sort_index()
        lines.append("**Distribution of StreetLight zones per UXsim link (matched only)**\n")
        lines.append("| Zones per link | # UXsim links |\n| --- | --- |")
        for k, v in cov.items():
            lines.append(f"| {k} | {v:,} |")
        lines.append("")

        lines.append("### Sample of matched links (top 15 by observed volume)\n")
        cols = [
            "osm_way_id",
            "observed_volume",
            "observed_avg_speed_mph",
            "n_streetlight_zones",
            "length_m",
            "free_flow_speed_ms",
            "lanes",
        ]
        top = matched.sort_values("observed_volume", ascending=False).head(15)
        header = "| " + " | ".join(["uxsim_link_name"] + cols) + " |"
        sep = "| " + " | ".join(["---"] * (len(cols) + 1)) + " |"
        lines.append(header)
        lines.append(sep)
        for link_name, r in top.iterrows():
            row_cells = [str(link_name)]
            for c in cols:
                v = r[c]
                if pd.isna(v):
                    row_cells.append("")
                elif isinstance(v, float):
                    row_cells.append(f"{v:,.1f}" if abs(v) >= 1 else f"{v:.3f}")
                else:
                    row_cells.append(str(v))
            lines.append("| " + " | ".join(row_cells) + " |")
        lines.append("")

    lines.append("## Notes\n")
    lines.append(
        "- UXsim's OSM importer is officially **experimental**. Expect "
        "dead-ends, fragmented links, and occasional unrealistic free-flow "
        "speeds. Address with `data/network/overrides.yaml`."
    )
    lines.append(
        "- The match rate above is per UXsim link. Unmatched links are "
        "usually short connectors or motorway ramps for which StreetLight "
        "did not export a zone. The opposite is also true: StreetLight "
        "zones outside the Leonia bbox are ignored here."
    )
    lines.append("")

    (REPORTS_DIR / "02_network.md").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
