"""Phase 3: run a baseline UXsim simulation with placeholder gateway demand.

Run from the repo root:

    venv/bin/python scripts/04_run_baseline.py

This is the first end-to-end smoke test: load network, attach demand,
simulate, and print summary statistics. Calibration (Phase 4) refines
the parameters used here.

Outputs:

    reports/04_baseline.md
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import pandas as pd

from leonia_traffic.config import REPORTS_DIR
from leonia_traffic.simulation.world_factory import build_baseline


def main() -> None:
    print("Building baseline World...")
    build = build_baseline(
        name="leonia_baseline",
        tmax=2 * 3600,
        deltan=10,
        duration_hours=2.0,
        daily_to_peak_factor=0.10,
        gwb_share=0.6,
        min_gateway_volume=500.0,
        print_mode=1,
    )
    W = build.world
    print(
        f"Demand attached: {build.demand_summary.n_demands_added} entries, "
        f"total flow {build.demand_summary.total_flow_vph:,.0f} veh/h"
    )

    print("Running simulation...")
    W.exec_simulation()
    print("Simulation finished.")

    stats = capture_stats(W)
    write_report(stats, build)
    print(f"Report at {REPORTS_DIR / '04_baseline.md'}")


def capture_stats(W) -> dict:
    a = W.analyzer
    a.basic_analysis()
    n_platoons = len(W.VEHICLES)
    deltan = W.DELTAN
    return {
        "n_vehicles_demanded": int(n_platoons * deltan),
        "n_vehicles_completed": int(getattr(a, "trip_completed", 0)),
        "n_vehicles_all": int(getattr(a, "trip_all", n_platoons * deltan)),
        "average_travel_time_s": float(getattr(a, "average_travel_time", float("nan"))),
        "average_delay_s": float(getattr(a, "average_delay", float("nan"))),
        "tmax_s": int(W.TMAX),
        "deltan_platoon_size": int(deltan),
        "n_links": len(W.LINKS),
        "n_nodes": len(W.NODES),
    }


def write_report(stats: dict, build) -> None:
    lines = ["# Phase 3 — baseline simulation\n"]
    lines.append(
        "_Auto-generated by `scripts/04_run_baseline.py`. This is the first "
        "end-to-end smoke run: placeholder gateway demand calibrated only by "
        "a global daily-to-peak factor. Phase 4 (Nelder-Mead calibration) "
        "tightens the fit._\n"
    )
    lines.append("## Simulation stats\n")
    lines.append("| Metric | Value |\n| --- | --- |")
    for k, v in stats.items():
        if isinstance(v, float):
            lines.append(f"| {k} | {v:,.2f} |")
        else:
            lines.append(f"| {k} | {v:,} |")
    lines.append("")

    lines.append("## Demand model\n")
    lines.append(f"- Demands added: {build.demand_summary.n_demands_added}")
    lines.append(
        f"- Total inflow: {build.demand_summary.total_flow_vph:,.0f} veh/h"
    )
    if build.demand_summary.notes:
        lines.append("- Notes:")
        for n in build.demand_summary.notes[:10]:
            lines.append(f"  - {n}")
    lines.append("")
    (REPORTS_DIR / "04_baseline.md").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
